apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: lidar-converter-server
build:
  artifacts:
    - image: nexus-docker-public-hosted.ossim.io/lidar-converter-server
      jib: {}
deploy:
  helm:
    releases:
      - name: lidar-converter-server
        chartPath: chart
