apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: lidar-converter-server
build:
  artifacts:
  - image: nexus-docker-public-hosted.ossim.io/lidar-converter-server
    jib: {}
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: lidar-converter-server
      chartPath: chart
