---
apiVersion: v1
kind: ConfigMap
metadata:
    name: lidar-converter-server
    labels:
        app: lidar-converter-server
data:
    application.yaml: |-
        lidar:
            converter:
              potree:
                outputDirectory: /output
              entwine:
                outputDirectory: /output
            indexer:
                endpoint: http://${LIDAR_INDEXER_SERVICE_HOST}:${LIDAR_INDEXER_SERVICE_PORT}
