---
apiVersion: v1
kind: ConfigMap
metadata:
    name: lidar-converter-server
    labels:
        app: lidar-converter-server
data:
    application.yaml: |-
        lidar:
            converter:
              potree:
                inputDirectory: /input
                outputDirectory: /output
              entwine:
                inputDirectory: /input
                outputDirectory: /output
